version: "3"

services:
    pin-status:
        build:
            dockerfile: Dockerfile
            context: .
        container_name: status-pin-api-container
        ports:
            - "8080:8080"
        environment:
            - FLASK_RUN_HOST=0.0.0.0
            - FLASK_RUN_PORT=8080
            - FLASK_ENV=development
            - LOG_LEVEL=INFO
        command: gunicorn -b 0.0.0.0:8080 main:app --workers=1 --threads=1 --timeout 90 --log-level warning