kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: api-gateway
  namespace: hpa-sms-status
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  targetCPUUtilizationPercentage: 300