apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: homol-status-pin-api-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: homol-status-pin-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70